import type { App } from 'vue';
import {
  create,
  // NConfigProvider,
  // NMessageProvider,
  // NDialogProvider,
  NInput,
  // NButton,
  // NForm,
  // NFormItem,
  // NCheckboxGroup,
  // NCheckbox,
  // NIcon,
  // NLayout,
  // NLayoutHeader,
  // NLayoutContent,
  // NLayoutSider,
  // NMenu,
  // NDropdown,
  // NSpace,
  // NTooltip,
  // NCard,
  // NSwitch,
  // NAlert,
  // NElement,
  // NTag,
  // NNotificationProvider,
  // NDatePicker,
  // NGrid,
  // NGridItem,
  // NDataTable,
  // NPopover,
  // NPagination,
  // NSelect,
  // NRadioGroup,
  // NRadio,
  // NTable,
  // NInputNumber,
  // NModal,
  // NUpload,
  // NUploadTrigger,
  // NSpin,
  // NTimePicker,
} from 'naive-ui';

const naive = create({
  components: [
    // NMessageProvider,
    // NDialogProvider,
    // NConfigProvider,
    NInput,
    // NButton,
    // NForm,
    // NFormItem,
    // NCheckboxGroup,
    // NCheckbox,
    // NIcon,
    // NLayout,
    // NLayoutHeader,
    // NLayoutContent,
    // NLayoutSider,
    // NMenu,
    // NDropdown,
    // NSpace,
    // NTooltip,
    // NCard,
    // NSwitch,
    // NAlert,
    // NElement,
    // NTag,
    // NNotificationProvider,
    // NDatePicker,
    // NGrid,
    // NGridItem,
    // NDataTable,
    // NPopover,
    // NPagination,
    // NSelect,
    // NRadioGroup,
    // NRadio,
    // NTable,
    // NInputNumber,
    // NModal,
    // NUpload,
    // NUploadTrigger,
    // NSpin,
    // NTimePicker,
  ],
});

export function setupNaive(app: App<Element>) {
  app.use(naive);
}
